server {
    listen 80;
    server_name aisolution.uz www.aisolution.uz;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 200 'Server is being configured...';
        add_header Content-Type text/plain;
    }
}
